//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_PayConceptsModels_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_PayConceptsModels_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
  
    ViewBag.Title = "Conceptos de Pago Pagina Principal";


#line default
#line hidden

#line 3 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
__o = Html.ActionLink("Crear nuevo", "Create");


#line default
#line hidden

#line 4 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Id);


#line default
#line hidden

#line 5 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Nombre);


#line default
#line hidden

#line 6 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Description);


#line default
#line hidden

#line 7 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.PayConceptsState);


#line default
#line hidden

#line 8 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
foreach (var item in Model) {
    

#line default
#line hidden

#line 9 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Id);


#line default
#line hidden

#line 10 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Nombre);


#line default
#line hidden

#line 11 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Description);


#line default
#line hidden

#line 12 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.PayConceptsState);


#line default
#line hidden

#line 13 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.ActionLink("Edit", "Edit", new { id=item.Id });


#line default
#line hidden

#line 14 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.ActionLink("Details", "Details", new { id=item.Id });


#line default
#line hidden

#line 15 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
       __o = Html.ActionLink("Delete", "Delete", new { id=item.Id });


#line default
#line hidden

#line 16 "C:\Users\joand\AppData\Local\Temp\3F042A385105FBFF25DE55A8C30E255BD07B\7\CuentasXPagar\Views\PayConceptsModels\Index.cshtml"
         
}

#line default
#line hidden
}
}
}
